#!/usr/bin/env python3

import sys
import os

import numpy
import nibabel

progname = os.path.basename(sys.argv[0])

if not os.path.exists('data'):
    os.mkdir('data')
elif not os.path.isdir('data'):
    print(f'{progname}: data is not a directory', file=sys.stderr)
    sys.exit(1)

if not os.path.exists('data/test_1.nii.gz'):
    data = numpy.fromiter(range(2*3*4), dtype='short')
    data.shape = (4, 3, 2)
    data = numpy.moveaxis(data, [0, 1, 2], [2, 1, 0])
    transform = [ [ 1, 0, 0, 0 ], 
                  [ 0, 1, 0, 0 ], 
                  [ 0, 0, 1, 0 ], 
                  [ 0, 0, 0, 1 ] ]
    transform = numpy.array(transform, dtype=numpy.dtype('float32'))
    vol = nibabel.Nifti1Image(data, transform)
    nibabel.save(vol, 'data/test_1.nii.gz')

if not os.path.exists('data/test_2.nii.gz'):
    data = numpy.array(range(2*3*4), dtype='short')
    data.shape = (4, 3, 2)
    data = numpy.moveaxis(data, [0, 1, 2], [2, 1, 0])
    transform = [ [ 1, 0, 0, 0 ], 
                  [ 0, 2, 0, 0 ], 
                  [ 0, 0, 3, 0 ], 
                  [ 0, 0, 0, 1 ] ]
    transform = numpy.array(transform, dtype=numpy.dtype('float32'))
    vol = nibabel.Nifti1Image(data, transform)
    nibabel.save(vol, 'data/test_2.nii.gz')

if not os.path.exists('data/test_3.nii.gz'):
    data = numpy.array([ 17**i % 31 for i in range(4*3*2) ], dtype='short')
    data.shape = (2, 3, 4)
    data = numpy.moveaxis(data, [0, 1, 2], [2, 1, 0])
    transform = [ [ 1,  2,  3,  4 ], 
                  [ 5,  6,  7,  8 ], 
                  [ 9, 10, 11, 12 ], 
                  [ 0,  0,  0,  1 ] ]
    transform = numpy.array(transform, dtype=numpy.dtype('float32'))
    vol = nibabel.Nifti1Image(data, transform)
    nibabel.save(vol, 'data/test_3.nii.gz')

sys.exit(0)

# eof
